language: python
python:
  - "3.8"

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "swe1-app"
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-028210901732"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY